# Generated by Django 5.2.6 on 2025-11-13 11:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_old_price_product_new_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('face', 'Visage'), ('lips', 'Lèvres'), ('eyes', 'Yeux'), ('eyebrow', 'Sourcils'), ('hair', 'Cheveux'), ('other', 'Other'), ('body', 'Corps'), ('packs', 'Packs'), ('acne', 'Acné'), ('hyper_pigmentation', 'Hyper pigmentation'), ('brightening', 'Éclaircissement'), ('dry_skin', 'Peau sèche'), ('combination_oily', 'Peau mixte/grasse')], db_index=True, default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('cod', 'Paiement à la livraison'), ('card', 'Carte/En ligne')], default='cod', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('canceled', 'Annulée')], default='pending', max_length=12)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('items_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, default='', max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant')),
            ],
        ),
    ]
