# Generated by Django 5.2.6 on 2025-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_old_price_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('face', 'Face'), ('lips', 'Lips'), ('eyes', 'Eyes'), ('eyebrow', 'Eyebrow'), ('hair', 'Hair'), ('body', 'Corps'), ('packs', 'Packs'), ('acne', 'Acné'), ('hyper_pigmentation', 'Hyper pigmentation'), ('brightening', 'Éclaircissement'), ('dry_skin', 'Peau sèche'), ('combination_oily', 'Peau mixte/grasse'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
