# Generated by Django 5.2.6 on 2025-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
