# Generated by Django 5.2.6 on 2025-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productvariant_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="public_token",
            field=models.CharField(
                max_length=64,
                unique=True,
                null=True,      # ✅ IMPORTANT
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),
    ]