# Generated by Django 5.2.6 on 2026-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_order_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('makeup', 'Maquillage'), ('face', 'Visage'), ('lips', 'Lèvres'), ('eyes', 'Yeux'), ('eyebrow', 'Sourcils'), ('hair', 'Cheveux'), ('other', 'Other'), ('body', 'Corps'), ('packs', 'Packs'), ('acne', 'Acné'), ('hyper_pigmentation', 'Hyper pigmentation'), ('brightening', 'Éclaircissement'), ('dry_skin', 'Peau sèche'), ('combination_oily', 'Peau mixte/grasse')], db_index=True, default='other', max_length=30),
        ),
    ]
